#!/bin/bash

# This script follows https://medium.com/@pierrepaci/deploy-tensorflow-object-detection-model-in-less-than-5-minutes-604e6bb0bb04
echo "Commencing docker build..."

# Change the model_url to relative Tensorflow pretrained model you wish to use
docker build -t object-detect . --build-arg model_url=http://download.tensorflow.org/models/object_detection/ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03.tar.gz
wait 
echo "Docker image built"
echo " "
echo "Use \'docker container ls\' to check running dockers"
echo "Kill containers using \'docker kill [container ID]\'"
echo " "
echo "Running docker..."
docker run -p 8080:8080 -p 8081:8081 object-detect

