#!/bin/bash

# This script follows https://medium.com/@pierrepaci/deploy-tensorflow-object-detection-model-in-less-than-5-minutes-604e6bb0bb04
echo "Commencing docker build..."

# Change the model_url to relative Tensorflow pretrained model you wish to use
docker build -t faster-rcnn-resnet50-coco . --build-arg model_url=http://download.tensorflow.org/models/object_detection/faster_rcnn_resnet50_coco_2018_01_28.tar.gz
wait 
echo "Docker image built"
echo " "
echo "Use \'docker container ls\' to check running dockers"
echo "Kill containers using \'docker kill [container ID]\'"
echo " "
echo "Running docker..."
docker run -p 8080:8080 -p 8081:8081 faster-rcnn-resnet50-coco

